### ISSUE TITLE
New-K2Package Category does not work with nested path

### ISSUE THREAD

**Issue by claytonwfirth** [dudelis/k2-management-pack#22]
If i pass a nested path to the category field of the New-K2Package command no output is created.

New-K2Package -Category "Client\Common" 

Instead i need to pass 
New-K2Package -Category "Common" 

which includes all categories where Common is in the path. 

It would be nice to allow nested categories to be passed.

**Comment by dudelis** [comment]
Unfortunately, this is not possible OOB. So I can package either by the category name OR using some xml file and package item by item. Nesting categories are not supported OR at least, I do not know what to pass. I tried various options and never succeeded. But let's have the issue logged, i will check it once again.

**Comment by claytonwfirth** [comment]
I'm happy to take a look at the code and see what i can come up with too.. Thanks for the quick response.

**Comment by dudelis** [comment]
Yes, feel free to check it. But please, note, that the approach I am using is not documented and the SourceCode has never made any announcements, saying this is a supported way of creating the packages. So I assume, this is not supported. ;)
